### ISSUE TITLE
Advice about datetime format

### ISSUE THREAD

**Issue by davidrendall** [bullhorn/dataloader#108]
Hi, this is not so much an issue, more a request for clarification. What date formats are supported in the CSV data? Also, what text qualifiers are OK to use in the CSV?

**Comment by ndickerson** [comment]
Hi David, In the dataloader.properties file, Section 4, we provide a link to the Java simple data format that is supported: http://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html

There is an examples section on that page that might be helpful:

```
"yyyy.MM.dd G 'at' HH:mm:ss z"      2001.07.04 AD at 12:08:56 PDT
"EEE, MMM d, ''yy"                  Wed, Jul 4, '01
"h:mm a"                            :08 PM
"hh 'o''clock' a, zzzz"             12 o'clock PM, Pacific Daylight Time
"K:mm a, z"                         :08 PM, PDT
"yyyyy.MMMMM.dd GGG hh:mm aaa"      02001.July.04 AD 12:08 PM
"EEE, d MMM yyyy HH:mm:ss Z"        Wed, 4 Jul 2001 12:08:56 -0700
"yyMMddHHmmssZ"                     010704120856-0700
"yyyy-MM-dd'T'HH:mm:ss.SSSZ"        2001-07-04T12:08:56.235-0700
"yyyy-MM-dd'T'HH:mm:ss.SSSXXX"      2001-07-04T12:08:56.235-07:00
"YYYY-'W'ww-u"                      2001-W27-3

```

We ended up picking a default, but we know that date formats range wildly in input data, we we provide the dataFormat property in the dataloader.properties file.  There is also a listDelimiter, which is used to break up multiple values in a One-To-Many field, such as `skills.name` or `businessSectors.name`.  

Does that help answer the question?

**Comment by davidrendall** [comment]
Thanks Nathan, yes that answers my question perfectly. I never thought to look in the .properties file.

**Comment by ndickerson** [comment]
Excellent, I am marking the issue resolved!
