### ISSUE TITLE
Delete All Custom Objects Associated With An Entity

### ISSUE THREAD

**Issue by C-Post** [bullhorn/dataloader#239]
Custom Objects in Bullhorn do not appear to be sortable.  To work around this, we discovered that we can first delete all of the existing objects and then (re)load them using a single threaded instance and a sorted load file.  

It would be a lot easier if we were able to sort custom object in Bullhorn but that aside - Is it possible to delete all of the custom objects associated with a specific entity without having all of the unique custom object ids?

**Comment by ndickerson** [comment]
Closing this since the work to allow mass deleting of custom objects is not planned future work.
