### ISSUE TITLE
Add new Locations entity

### ISSUE THREAD

**Issue by ddonathan** [bullhorn/dataloader#301]
Locations were introduced as a standard entity in R2019.10. Can we have this added to the dataloader?

**Comment by dbroking-sixcel** [comment]
@ndickerson - trying to find out the state of adding location (along with invoice terms and billing profile) to the sdk-rest - can you kindly point me to the right place to look/watch for these things by chance?

**Comment by ndickerson** [comment]
It exists in the sdk-rest currently. Here's the pull request in dataloader that is almost finished: https://github.com/bullhorn/dataloader/pull/315.
