### ISSUE TITLE
Credentials validation issues

### ISSUE THREAD

**Issue by SanneD** [bullhorn/dataloader#316]
### Description

Hi guys,

I got the age-old issue of not being able to get my credentials verified.. 
When I Open the Data Loader desktop app, I add in my Username, Password, ClientID and Client secret and when I then keep 'Check Credentials' it states: Login Failed.

I tried with my personal Username AND with the API username and password which I have reset as per the instructions.

I also checked the ClientID and Secret, copied it across a few times. I also manually typed both of them out and still no luck.

Any other ideas of where I should look to get in?

![image](https://user-images.githubusercontent.com/65000234/81365724-462a7e80-912c-11ea-8a1b-62eb3004531f.png)
![image](https://user-images.githubusercontent.com/65000234/81365824-8689fc80-912c-11ea-91bb-c3396676f584.png)

**Comment by marelleb** [comment]
Hi Sanne, if you haven't done so already I would recommend speaking with Bullhorn Support so they can verify the client ID and secret are correct. You may also want to ask them to double check that the terms of service are omitted for this specific key (this is needed when the ID and secret are used for the dataloader)
