### ISSUE TITLE
Feature request: have the option to skip duplicates instead of updating them

### ISSUE THREAD

**Issue by marelleb** [bullhorn/dataloader#317]
### Description

Feature Request: Would it be possible to add an option in the Duplicate Check step to skip the row if a match is found?

### Steps to Reproduce

1. Spreadsheet contains 5 candidates: 3 new candidates and 2 that already exist in the database
2. Enable Duplicate Check and set field to Email
3. Load the file

##### Current behavior:

3 new candidates get created, and the 2 existing candidates get updated with the information from the spreadsheet.

##### Desired behavior:

Have the ability to skip rows based on duplicate check: 3 candidates get created, and the 2 existing candidates do not get touched.

**Comment by ndickerson** [comment]
Added the skip duplicates optional setting - will be included in the Data Loader 4.9.0 release today
