### ISSUE TITLE
Location - missing required property: effectiveDate error - while effectiveDate is included in csv file

### ISSUE THREAD

**Issue by dbroking-sixcel** [bullhorn/dataloader#319]
### Description

Location - missing required property: effectiveDate error - while effectiveDate is included in csv file

### Steps to Reproduce

1.  Attached properties file
2.  Attached location.csv file

##### Expected behavior:

Location data to successfully load

##### Actual behavior:

All records fail with the following message...

Row xxx: com.bullhornsdk.data.exception.RestApiException: {"errorMessage":"error persisting an entity of type: Location","errorMessageKey":"errors.cannotPersistEntity","errorCode":500,"errors":[{"detailMessage":"missing required property: effectiveDate","propertyName":"effectiveDate","severity":"ERROR","type":"MISSING_REQUIRED_PROPERTY"}],"entityName":"Location"}

##### Reproduces how often:

100%

### Additional Information

1. The `dataloader.properties` file (minus login info)
2. The CSV input file (smallest possible file that reproduces the issue)
3. The results file(s)
4. The log file

[dataloader_2020-07-07_20.35.20.log](https://github.com/bullhorn/dataloader/files/4887742/dataloader_2020-07-07_20.35.20.log)

[location.zip](https://github.com/bullhorn/dataloader/files/4887743/location.zip)

[location_load_2020-07-07_20.35.20_failure.zip](https://github.com/bullhorn/dataloader/files/4887747/location_load_2020-07-07_20.35.20_failure.zip)

[BAK-dataloader.zip](https://github.com/bullhorn/dataloader/files/4887754/BAK-dataloader.zip)

**Comment by ndickerson** [comment]
I don't see anything unusual about the setup, other than the column mapping is setup for effectiveDate when it really doesn't need to be. It's mapping effectiveDate to effectiveDate. The column mapping is really just for column names that should be ignored, or making a column alias. Is this still an issue?

**Comment by desaironakgit** [comment]
I am facing the same issue. Can someone provide what was the solution
