### ISSUE TITLE
Opportunity - Duplicate To-One Associations Error - But Duplicates do not exist

### ISSUE THREAD

**Issue by dbroking-sixcel** [bullhorn/dataloader#323]
[opportunity_load_2020-09-28_15.09.12_failure-csv.txt](https://github.com/bullhorn/dataloader/files/5300126/opportunity_load_2020-09-28_15.09.12_failure-csv.txt)
### Description

When loading Opportunities - we are getting a duplicate To-One Associations error.

[dataloader_2020-09-28_15.09.12.log](https://github.com/bullhorn/dataloader/files/5300094/dataloader_2020-09-28_15.09.12.log)

[opportunity-csv.txt](https://github.com/bullhorn/dataloader/files/5300098/opportunity-csv.txt)
 
### Steps to Reproduce

1.  log file attached
2.  input file attached
3.  results file attached
4.  corporation id = 20381
5.  confirmed that duplicate contacts do not exist in database

##### Expected behavior:

opportunities should get loaded without error

##### Actual behavior:

receive duplicate to-one associations error on every record trying to be loaded

##### Reproduces how often:

100%

### Additional Information

1. The `dataloader.properties` file (minus login info)
2. The CSV input file (smallest possible file that reproduces the issue)
3. The results file(s)
4. The log file

**Comment by dbroking-sixcel** [comment]
@ndickerson  - under some amount of time constraint with this issue - appreciate whatever help can be offered

**Comment by ndickerson** [comment]
Looking at the attached log file, it states that these are the IDs of the client contacts that are coming back as duplicates:

Data Loader makes the call to look for non-deleted contacts with a matching External ID:

`Find(ClientContact Search): externalID: Contacts_4237994000001174272 AND isDeleted:0, fields: [externalID, id, isDeleted]`

Then it reports back that it found these 199 matches:

`Adding Cache Entry from Rest Call: 199 entities: [13429, 13316, 13317, 13318, 13319, 13320, 13321, 13322, 13323, 13324, 13325, 13326, 13327, 13328, 13329, 13330, 13331, 13332, 13333, 13334, 13335, 13336, 13337, 13338, 13339, 13340, 13341, 13342, 13343, 13344, 13345, 13346, 13347, 13348, 13349, 13350, 13351, 13352, 13353, 13354, 13355, 13356, 13357, 13358, 13359, 13360, 13361, 13362, 13363, 13364, 13365, 13366, 13367, 13368, 13369, 13370, 13371, 13372, 13373, 13374, 13375, 13376, 13377, 13378, 13379, 13380, 13381, 13382, 13383, 13384, 13385, 13386, 13387, 13388, 13389, 13390, 13391, 13392, 13393, 13394, 13395, 13396, 13397, 13398, 13399, 13400, 13401, 13402, 13403, 13404, 13405, 13406, 13407, 13408, 13409, 13410, 13411, 13412, 13413, 13414, 13415, 13416, 13417, 13418, 13419, 13420, 13421, 13422, 13423, 13424, 13425, 13426, 13427, 13428, 13430, 13431, 13432, 13433, 13434, 13435, 13436, 13437, 13438, 13439, 13440, 13441, 13442, 13443, 13444, 13445, 13446, 13447, 13448, 13449, 13450, 13451, 13452, 13453, 13454, 13455, 13456, 13457, 13458, 13459, 13460, 13461, 13462, 13463, 13464, 13465, 13466, 13467, 13468, 13469, 13470, 13471, 13472, 13473, 13474, 13475, 13476, 13477, 13478, 13479, 13480, 13481, 13482, 13483, 13484, 13485, 13486, 13487, 13488, 13489, 13490, 13491, 13492, 13493, 13494, 13495, 13496, 13497, 13498, 13499, 13500, 13501, 13502, 13503, 13504, 13505, 13506, 13507, 13508, 13509, 13510, 13511, 13512, 13513, 13514]`

I would suggest searching for those IDs in the Contact List and inspecting the `externalID`s on those records.

**Comment by dbroking-sixcel** [comment]
@ndickerson  - thanks for the reply!

I wish this issue was that simple - I neglected to mention during my original submission of this case that we did confirm prior to submitting this case that there are no duplicates external ID values present.  It is also worth calling out that the 199 count coming back represents every contact on file.

we validated that no duplicates exists in two ways - 

1) via the UI - see attached print screen
2) connected with Shreeda Vyas and she was also able to confirm no duplicates existed via the database level

not sure where to go from here - thanks in advance for your help!

[Alaris Contact Sample.docx](https://github.com/bullhorn/dataloader/files/5305338/Alaris.Contact.Sample.docx)

**Comment by ndickerson** [comment]
Let's try this: when you're logged into Bullhorn as that same user, what happens when you make the GET call (you can paste this into your browser, The RESTURL will be the specific rest url that precedes the /search in your network tab calls): 

`{{RESTURL}}/services/dataLoader/getByExternalID?entity=ClientContact&fields=id,name,externalID&externalId=`{{RESTURL}}/search/ClientContact?fields=id,name,externalID&query=externalID= Contacts_4237994000001174272`

How about when you make the call:

`{{RESTURL}}/search/ClientContact?fields=id,name,externalID&query=externalID= Contacts_4237994000001174272`

Those are the two calls that Data Loader makes to lookup records by external ID. If the first one works, it uses that. If it fails it then falls back to the second.

Try those and let me know what you get, that should pinpoint the problem.

**Comment by dbroking-sixcel** [comment]
@ndickerson  - thanks for the reply

please attached - in short we getting zero records returned when making those API calls

when searching by external ID within the UI - we're getting all contacts returned (199)

please let us know what else we can provide

[Alaris API Call Response.docx](https://github.com/bullhorn/dataloader/files/5312140/Alaris.API.Call.Response.docx)

**Comment by ndickerson** [comment]
Try turning off `wildcardMatching=true` in your properties file and see if that fixes it.

**Comment by dbroking-sixcel** [comment]
@ndickerson   we have a winner!!!!
thanks so much for your help!
