### ISSUE TITLE
Custom Object Updates not working as Expected

### ISSUE THREAD

**Issue by shilpal3** [bullhorn/dataloader#327]
Custom Object Updates not working as Expected
[ClientCorporation_Custom OBject_Load.docx](https://github.com/bullhorn/dataloader/files/5410066/ClientCorporation_Custom.OBject_Load.docx)

1. Do a first run with the dataloader where you duplicate check on "clientCorporation.externalID" and "text1"
2. The dataloader should tell you that it updated records successfully, but when you look in the system you're not seeing any changes. That's ok.
3. You then open the results file, and you remove the "dataloader_action" column (column B), like this:
 
4. Save this spreadsheet as a new file 
5. You will then need to change the duplicate check in the properties file to "id"
6. You can now run the dataloader a second time, and it should now correctly update the dates in the custom object entry
 
The screenshot above is from a test I ran, so when you look in your database for this company record, you fill find that it has correctly updated the date (keep in mind that dates require you to either set a time, or to move everything one day forward in the spreadsheet for the correct date to be entered in the system).
 

##### Expected behavior:

[What you expect to happen]

##### Actual behavior:

[What actually happens]

##### Reproduces how often:

[What percentage of the time does it reproduce?]

### Additional Information

1. The `dataloader.properties` file (minus login info)
2. The CSV input file (smallest possible file that reproduces the issue)
3. The results file(s)
4. The log file

**Comment by ndickerson** [comment]
So it sounds like there are two things going on here:

1. The uploaded name of the custom object: "MBE – Minority-owned BusinessEnterprise" is showing up as: "MBE **<?>** Minority-owned BusinessEnterprise"

There are multiple formats that the CSV file can be saved in. The default is UTF-8 (multibyte). However, an older format (single byte) is sometimes still used, which will result in question mark characters. You can either set the flag in Data Loader: singleByteEncoding to true, or save the CSV file as UTF-8. 

2. The re-load of the same data is creating duplicates. I'm not see the whole picture here. The data in the provided word doc is showing one single load of one single record for ClientCorporationCustomObject4, and one for ClientCorporationCustomObject5. If you look at the examples that ship with Data Loader, insert/export/update/delete are continuously being tested for custom objects such as these. If you feel you have reached an error state with the custom object loading, please attach to this issue the exact log files for the load. The log files I have seen so far appear to be working, and are reporting back the Client Corporation ID, the exact query being made for the Custom Object on that Client Corporation, and showing the resulting Custom Object being created.

**Comment by shilpal3** [comment]
Thank you. We will try the format as suggested. The date when we load as 10/11/2019 , its taking it as 01/11/2019. that's the other issue and inspite of checking isduplicate, the duplicate records are inserted

**Comment by Madhurima12-TCS** [comment]
Hi  ,  

1. Saving the CSV as UTF-8 did work - Thank you  . 

2. However the second part of it , we have the same opinion as you that according to log files , the load looks good. But we do not see the updates/inserts in the UI.  I tried to update/insert for the other random IDs that we had not tried, even that gives the same issue.

**Comment by ndickerson** [comment]
If the data is in the database, but it does not show up as you hope in the UI, then you will want to determine if it is in the correct format, and has all of the data filled out. Have you tried adding the data manually via the UI or Rest calls in order to determine the format for records that do show up properly? Surely there are ways of determining what that format is in order to ensure that what you are inserting via Data Loader is in fact the correct format, in terms of data fields that are filled out. This does not appear to be an issue with Data Loader, as Data Loader only inserts the data it is given, and if the UI requires data that is not provided, it might not render the records in the UI. Please compare the records you are uploading to other records that are showing up properly in the UI.
