### ISSUE TITLE
Placement Entity: Unable to view the update of data on Placement Fee(Flat) field using dataloader

### ISSUE THREAD

**Issue by Shamshadbegam** [bullhorn/dataloader#328]
Unable to view the update of data on Placement Fee(Flat) field once it is updated using dataloader
[Description of the issue]

Please find the attached Input Spreadsheet and the Success file.

[FlatFee.zip](https://github.com/bullhorn/dataloader/files/5414953/FlatFee.zip)

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

##### Expected behavior:

[What you expect to happen]

##### Actual behavior:

[What actually happens]

##### Reproduces how often:

[What percentage of the time does it reproduce?]

### Additional Information

1. The `dataloader.properties` file (minus login info)
2. The CSV input file (smallest possible file that reproduces the issue)
3. The results file(s)
4. The log file

**Comment by ndickerson** [comment]
The spreadsheet and success file show that the single record was updated in the database. As far as the Data Loader is concerned, this is correct. 

The viewing of the data is configured through the particular Corporation, User and Private Label settings via the ATS and support. Closing this issue as a non-Data Loader issue. If you feel that there is an issue with the loading of data, and Data Loader in particular, feel free to create an issue request for that, and please do supply all of the required information for a Data Loader issue, including log files.
