### ISSUE TITLE
JobSubmission Entity: Unable to Export data from command prompt using Export Command

### ISSUE THREAD

**Issue by Shamshadbegam** [bullhorn/dataloader#331]
### Description
JobSubmission Entity: Unable to Export data from command prompt using Export Command
[Description of the issue]
JobSubmission Entity: Unable to Export data from command prompt using Export Command by using the data of candidate.externalID/jobOrder.externalID/candidate.externalID and jobOrder.externalID in the input spreadsheet in BH Staging

Properties File :
Section 3 -- Exist Fields
jobSubmissionExistField=candidate.externalID/jobOrder.externalID/candidate.externalID,jobOrder.externalID
[DataExport.zip](https://github.com/bullhorn/dataloader/files/5422499/DataExport.zip)

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

##### Expected behavior:

[What you expect to happen]

##### Actual behavior:

[What actually happens]

##### Reproduces how often:

[What percentage of the time does it reproduce?]

### Additional Information

1. The `dataloader.properties` file (minus login info)
2. The CSV input file (smallest possible file that reproduces the issue)
3. The results file(s)
4. The log file

**Comment by ndickerson** [comment]
Sorry, but I cannot triage this issue as written. The issue template has not been filled out, and the required log file mentioned above has not been provided, neither have the steps to reproduce or the expected/actual behavior. 

Based on what was provided, there does not appear to be any issue with the way that Data Loader has operated given the input file and result file. If there is existing data that you wish to export to a CSV, you may either check the exist criteria in use and try again, or export directly from a list in the ATS to a CSV and skip this export step using Data Loader.
