### ISSUE TITLE
Trouble loading Custom Object Instances

### ISSUE THREAD

**Issue by Madhurima12-TCS** [bullhorn/dataloader#333]
Can you please assist on below items:

 1.Process to take backup of custom object instance fields as we don’t see ID’s on screen
 2.Is there any challenge from Data loader standpoint to update multi select fields and how  do we address the update feature for 
     supplier Information . We are not able to make update on multiselect fields .
 3.There was some limitation in number of Client ID’s we could insert into Approved Client name but we were able to update them via UI.
 4.Audit changes doesn’t reflect on UI.

**Comment by Madhurima12-TCS** [comment]
Hi,  

Can I get this assigned to someone please .

**Comment by ndickerson** [comment]
Sorry, this is not the right forum to address these sorts of issues. 

This forum is for issues with Data Loader itself, where the behavior is broken somehow from what it should do, and can be demonstrated clearly in a simple example that includes input files, results files and log files. See existing open issues for examples of this. 

These issues are really data shape and configuration issues, which are solved by changing settings in the ATS. To reflect data properly in the UI, the data you are loading will need to match the shape of the data that the UI is looking for. 

If you can isolate an issue to the Data Loader itself, then please submit an issue with all the required information for triage.

**Comment by Madhurima12-TCS** [comment]
Thanks  Nathan .  

Let me filter out the concern and see if i need anything specific to data loader .

**Comment by ndickerson** [comment]
If you can isolate an issue to the Data Loader itself, then please submit an issue with all the required information for triage that is in the Issue Template. Thanks.
