### ISSUE TITLE
Recruiter Backend Field Name?

### ISSUE THREAD

**Issue by shyamn2020** [bullhorn/dataloader#337]
### Description
Recruiter Backend Field Name in Notes
[Description of the issue]
We are trying to update the Recruiter name wherever possible and the Note example does not have it. Hence we need to identify what is the backend recruiter field name so that it could be updated.
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

##### Expected behavior:

[What you expect to happen]

##### Actual behavior:

[What actually happens]

##### Reproduces how often:

[What percentage of the time does it reproduce?]

### Additional Information

1. The `dataloader.properties` file (minus login info)
2. The CSV input file (smallest possible file that reproduces the issue)
3. The results file(s)
4. The log file

**Comment by ndickerson** [comment]
All possible fields that can be updated for Notes are available in the example file: https://github.com/bullhorn/dataloader/blob/master/examples/load/Note.csv

**Comment by ndickerson** [comment]
Is the `commentingPerson` field what you are looking for?
