### ISSUE TITLE
Candidate Entity:When Candidate Resume is uploaded for a Candidate using data loader in BH Experis Dev,Resume is not shown in the Overview tab under Resume but it is appearing in the Files tab of Candidate

### ISSUE THREAD

**Issue by Shamshadbegam** [bullhorn/dataloader#343]
### Description

Candidate Entity:When Candidate Resume is uploaded for a Candidate using data loader in BH Experis Dev,Resume is not shown in the Overview tab under Resume but it is appearing in the Files tab of Candidate

[Description of the issue]

Candidate Entity:When Candidate Resume is uploaded for a Candidate using data loader in BH Experis Dev,Resume is not shown in the Overview tab under Resume but it is appearing in the Files tab of Candidate

Resume uploaded is shown in the Files Tab of Candidate and which is not appearing in the Overview tab in Resume

### Steps to Reproduce

1. Connect to the BH Experis Dev by using the Experis Dev details in the Section1 of Dataloader Property file
2.For Resume upload for a Candidate it is defined in dataloader property file under section3 with "candidateExistField=id" 
3.Prepare input csv file for Candidate Resume upload
4.Run the dataloader using command prompt by using the command loadAttachments 
5.Success file is generated with insertion of Resume for candidate
6.Verify the Resume uploaded in Candidate Entity in BH Experis Dev UI in the Overview tab of Resume and Files Tab

##### Expected behavior:
Candidate Resume uploaded should be shown under the Resume,Overview Tab of Resume and Files Tab 

[What you expect to happen]
Candidate Resume uploaded should be shown under the Resume,Overview Tab of Resume along with Files tab 

##### Actual behavior:
Candidate Resume uploaded is not shown under the Resume,Overview Tab of Resume and it is shown only under Files Tab 

[dataloader_Property_file.txt](https://github.com/bullhorn/dataloader/files/5843446/dataloader_Property_file.txt)
##### Reproduces how often:
Performed the Resume upload for a Candidate with one Record so observed for this as of now

### Additional Information

1. The `dataloader.properties` file (minus login info)
[dataloader_Property_file.txt](https://github.com/bullhorn/dataloader/files/5843449/dataloader_Property_file.txt)
2. The CSV input file (smallest possible file that reproduces the issue)
[CandidateAttachFile_BHDev.xlsx](https://github.com/bullhorn/dataloader/files/5843476/CandidateAttachFile_BHDev.xlsx)
3. The results file(s)
[CandidateAttachFile_BHDev_loadAttachments_2021-01-20_17.47.42_success.xlsx](https://github.com/bullhorn/dataloader/files/5843482/CandidateAttachFile_BHDev_loadAttachments_2021-01-20_17.47.42_success.xlsx)
4. The log file
[dataloader_2021-01-20_17.47.42.log](https://github.com/bullhorn/dataloader/files/5843486/dataloader_2021-01-20_17.47.42.log)

Screenshots of BHUI:
![Overview_Resume_Tab](https://user-images.githubusercontent.com/73225817/105198301-89663980-5b63-11eb-8b21-48e05973449d.JPG)
![Resume_File_tab](https://user-images.githubusercontent.com/73225817/105198446-b0bd0680-5b63-11eb-9144-7e7f8dc6cfc3.JPG)

**Comment by ndickerson** [comment]
There is actually a second step required in order to get the candidate's description field to reflect the resume. It's discussed at length in the Wiki: https://github.com/bullhorn/dataloader/wiki/Commands#convertattachments. The files tab is for the raw resume file, and the description contains the HTML version of the resume. In order to do this, Data Loader provides a convert command that allows for offline conversion of the resume from PDF, Word, etc. to HTML. The conversion happens quite quickly and the HTML resumes are stored in a subfolder where they can then be uploaded using the load command.

**Comment by Shamshadbegam** [comment]
Thanks Nathan,

As suggested, performed the second step of convertAttachments using the command but still could not see the Resume under Overview tab of candidate.

Request you to provide your inputs.

Thanks,
Shamshad

**Comment by ndickerson** [comment]
The convertAttachments command is the first step actually. You then will need to perform a load command, making sure to use externalID as one of the columns, and the load comment will pick up the contents of the files, which are stored in the convertedAttachments directory under: `convertedAttachments/EntityName/externalID` and the files will get read in and loaded into the description field.

**Comment by Shamshadbegam** [comment]
Thanks Nathan,

Tried executing with the steps provided, first with convertAttachments and then load but still could not see the Resume under Overview tab of candidate and attached is the document with steps followed. Request you to review and suggest if the step/process/command followed is incorrect at any step during the execution.
[CandidateResumeUpload.docx](https://github.com/bullhorn/dataloader/files/5854993/CandidateResumeUpload.docx)

Regards,
Shamshad

**Comment by ndickerson** [comment]
The problem with screenshot in the attached docx file is that you're trying to load the same CSV file for convert attachments as you are for the candidate. After you run convertAttachments successfully, first ensure that the folder `candidate` exists in the directory you are running dataloader from, with subfolders for each candidate externalID provided in the conversion CSV. Then, when you go to load the candidate description, use a different CSV file, with only a single column, the externalID column. Then Data Loader will insert the description field as the content of the converted resume files in the subfolders.

**Comment by Shamshadbegam** [comment]
Thanks a lot Nathan,

After performed the convertAttachments a subfolder is created with foldername as convertedAttachments which has the subfolder Candidate and in which the html file.
![image](https://user-images.githubusercontent.com/73225817/105516083-771f0380-5cfb-11eb-81e3-3408821063c0.png)
And I used input file with only externalID column to load the file and below is the screenshot of the input csv file.
![image](https://user-images.githubusercontent.com/73225817/105516959-763aa180-5cfc-11eb-84a6-c226d0512b77.png)
but when executed the dataloader command load getting below error.
![image](https://user-images.githubusercontent.com/73225817/105517063-936f7000-5cfc-11eb-8f50-63662baf9d08.png)

Regards,
Shamshad

**Comment by ndickerson** [comment]
That's because the column needs to be called `externalID`, not `candidate.externalID`

**Comment by Shamshadbegam** [comment]
Thanks a lot Nathan.Now Resume data is populated in Overview tab and under Resume.
