### ISSUE TITLE
Missing fields in some Entities

### ISSUE THREAD

**Issue by leonardosalatino** [bullhorn/dataloader#345]
Is there some workaround when a field is missing in dataloader?
For example, on "ClientCorporation" the field "twitterHandle" is missing in data loader but is available in the API.

I think it is not a matter of just updating this code because when running a "dataloader template ClientCorporation" I don't get the field "twitterHandle".

Thanks

**Comment by ndickerson** [comment]
Yes, it is a matter of updating the https://github.com/bullhorn/sdk-rest and then updating Data Loader to pull in the latest version to use the new fields.

**Comment by ndickerson** [comment]
twitterHandle has been added in the latest release: https://github.com/bullhorn/dataloader/releases/tag/v4.10.1
