### ISSUE TITLE
ClientCorporation Entity : Getting error as ClientCorporation entity is not deletable when tried to perform delete operation

### ISSUE THREAD

**Issue by Shamshadbegam** [bullhorn/dataloader#347]
### Description
ClientCorporation Entity : Getting error as ClientCorporation entity is not deletable when tried to perform delete operation

[Description of the issue]

ClientCorporation Entity : Getting error as ClientCorporation entity is not deletable when tried to perform delete operation

When tried to delete ClientCorporation Id of ClientCorporation Entity getting error as ClientCorporation entity is not deletable

### Steps to Reproduce

1. Connect to the BH UAT by using the BH UAT details in the Section1 of Dataloader Property file
2. To perform delete of ClientCorporation Id it is defined in dataloader property file under section3 with "clientCorporationExistField=id"
3. Prepare input csv file for Candidate Resume upload
4. Run the dataloader using command prompt by using the command delete

##### Expected behavior:

Should be able to delete the ClientCorporation record of  ClientCorporation Entity

[What you expect to happen]

Should be able to delete the ClientCorporation record of  ClientCorporation Entity

##### Actual behavior:

When tried to delete ClientCorporation Id of ClientCorporation Entity getting error as ClientCorporation entity is not deletable

##### Reproduces how often:

Performed delete operation of ClientCorporation Id of ClientCorporation Entity with one record

### Additional Information 

1. [dataloader_Property_file.txt](https://github.com/bullhorn/dataloader/files/6131081/dataloader_Property_file.txt)

2. [ClientCorporationDeleteBHUAT.xlsx](https://github.com/bullhorn/dataloader/files/6131093/ClientCorporationDeleteBHUAT.xlsx)

3. The results file is not generated

4. [dataloader_2021-03-12_20.53.30.log](https://github.com/bullhorn/dataloader/files/6131104/dataloader_2021-03-12_20.53.30.log)

5. Screenshot of Command Prompt
![image](https://user-images.githubusercontent.com/73225817/110963272-e28a6680-8377-11eb-8155-854083559ed0.png)

Request you to provide your inputs on this if we can perform delete operation.

**Comment by ndickerson** [comment]
Sorry, Client Corporations are just not deletable in the data model. There is a section on this in the Wiki: https://github.com/bullhorn/dataloader/wiki/FAQs#q-how-do-i-delete-a-clientcorporation-using-dataloader
