### ISSUE TITLE
General Ledger Segment upload

### ISSUE THREAD

**Issue by leonardosalatino** [bullhorn/dataloader#349]
Are we able to upload GeneralLedgerSegments? I see we can upload GeneralLedgerAccounts; and in the API I can upload both. But data loader is returning the following error when I try to generate a template for Segments:

C:\Program Files (x86)\Bullhorn\dataloader1>dataloader template GeneralLedgerSegment1
ERROR: Could not determine entity from the name: "GeneralLedgerSegment1"

I tried with GeneralLedgerSegment and with the 5 numbers at the end; all return the same error.

Thanks

**Comment by ndickerson** [comment]
Adding this to the backlog. Will be doing this feature soon - no specifics on timeline, but it's being planned.

**Comment by ndickerson** [comment]
This has been added to the latest version of data loader.
