### ISSUE TITLE
Facing issue while uploading the converted resumes via dataloader to Bullhorn on a New Environment

### ISSUE THREAD

**Issue by shilpal3** [bullhorn/dataloader#351]
Facing issue while uploading the converted resumes via dataloader to Bullhorn on a New Environment

I have successfully converted the resumed to HTML files and on uploading the converted resumes, I ran into Error Code –“500” – Unknown Internal. This issue seems very specific to New Staging environment as am able to perform the resume load to other environment.

**Process Followed:**

Step1  -ConvertAttachments  was successful – convertAttachements -> Candidate -> Resumes of Candidates named as External ID’s 

candidate.externalID | externalID | relativeFilePath | isResume
MEX2 | resume-001 | C:\dataloader\examples\load\attachments\sampleFiles\Aaron     Manuel Lopez Barradas.pdf | 1
MEX1 | resume-001 | C:\dataloader\examples\load\attachments\sampleFiles\Luis_Antonio_Gonzalez_Cordoba_Resume     (2).pdf | 1

**Step 2: Upload Converted resume**

Source File
externalID
MEX1
MEX2

Property File:

candidateExistField=externalID 

**Error:**

Row 2: com.bullhornsdk.data.exception.RestApiException: {"errorMessage":"error persisting an entity of type: Candidate","errorMessageKey":"errors.cannotPersistEntity","errorCode":500,"errors":[{"detailMessage":"","propertyName":"","severity":"ERROR","type":"UNKNOWN_INTERNAL_ERROR"}],"entityName":"Candidate"}                                   Row 1: com.bullhornsdk.data.exception.RestApiException: {"errorMessage":"error persisting an entity of type: Candidate","errorMessageKey":"errors.cannotPersistEntity","errorCode":500,"errors":[{"detailMessage":"","propertyName":"","severity":"ERROR","type":"UNKNOWN_INTERNAL_ERROR"}],"entityName":"Candidate"}                                   Results of DataLoader run                                                                                                                                                   Start time: 2021-03-29 07:31:17                                                                                                                                             End time: 2021-03-29 07:31:33                                                                                                                                               Args: load C:\dataloader\data\Candidate_Update.csv                                                                                                                          Total records processed: 2                                                                                                                                                  Total records inserted: 0                                                                                                                                                   Total records updated: 0                                                                                                                                                    Total records deleted: 0                                                                                                                                                    Total records failed: 2                                                                                                                                                     Finished loading Candidate records in 00:00:16                                                                                   

### Details Attached:
[Candidate_Update_load_failure.xlsx](https://github.com/bullhorn/dataloader/files/6222368/Candidate_Update_load_failure.xlsx)
[dataloader.txt](https://github.com/bullhorn/dataloader/files/6222370/dataloader.txt)

[dataloader.txt](https://github.com/bullhorn/dataloader/files/6222317/dataloader.txt)
[dataloader_2021-03-29_07.31.15.log](https://github.com/bullhorn/dataloader/files/6222327/dataloader_2021-03-29_07.31.15.log)
[Candidate_Update_load_failure.xlsx](https://github.com/bullhorn/dataloader/files/6222344/Candidate_Update_load_failure.xlsx)

**Comment by ndickerson** [comment]
Does this work on other environments, but not this environment?

**Comment by shilpal3** [comment]
Yes, It works on other environment and am using only external ID to load the resume

**Comment by ndickerson** [comment]
Then this doesn't sound like a Data Loader specific issue since Data Loader uses the same rest calls in all environments

**Comment by shilpal3** [comment]
Thank you. I will request BH configuration team to review

**Comment by ndickerson** [comment]
Sounds great. Thanks.
