### ISSUE TITLE
DataLoader Missing JobOrder CustomText 21-40 fields

### ISSUE THREAD

**Issue by pmularski** [bullhorn/dataloader#354]
### Description

DataLoader is currently missing the JobOrder CustomText 21-40 fields. These are newer fields added to the schema, but are not available for use in the current version of DataLoader.

### Steps to Reproduce

1. Open DataLoader
2. Import ANY XML File
3. Select a field
4. Type customtext30
5. No data returns

##### Expected behavior:

All current JobOrder CustomText fields are available.

##### Actual behavior:

JobOrder CustomText 21-40 fields are not available for loading.

##### Reproduces how often:

100%

### Additional Information

No additional information. The fields just aren't available.

**Comment by ndickerson** [comment]
Adding this to the backlog. Will be doing this feature soon - no specifics on timeline, but it's being planned.

**Comment by ndickerson** [comment]
This is now fixed in release: https://github.com/bullhorn/dataloader/releases/tag/v4.10.1. Coming to the desktop app in the next business day or two.
