### ISSUE TITLE
Bullhorn Data Loader Adding Spaces to Names?

### ISSUE THREAD

**Issue by davidlinesq** [bullhorn/dataloader#360]
Hi everyone,

Some random candidates in our Bullhorn instance are having extra spaces added to the end of the First or Last names in Bullhorn.  Bullhorn support thinks that the data loader might be causing this to happen.  Has anyone ever experienced an issue with data loader adding spaces to candidates names (either First or Last)?

Thanks,
David

**Comment by ndickerson** [comment]
The Data Loader will strip whitespaces at the beginning/end of each cell of data in the CSV spreadsheet.

**Comment by davidlinesq** [comment]
I think the issue is that we are updating 3 specific fields (none of them name fields).  Bullhorn is saying that after we update those fields then the data loader is adding spaces to the First or Last name fields.  Does that make sense and is that even possible?

**Comment by ndickerson** [comment]
The Data Loader can take data from a CSV file and convert it into REST calls to insert/update records. When you say, "Then the data loader is adding spaces" - who is running the data loader exactly?

**Comment by davidlinesq** [comment]
I've been the only person running it until this week.

**Comment by ndickerson** [comment]
I'm not sure how that would ever happen. These issues are really for Data Loader bugs or feature requests. If it's a bug, then it needs to be reproducible. Sounds like more research is needed into what the root cause is.
