### ISSUE TITLE
Row 1: com.bullhornsdk.data.exception.RestApiException: {"errorMessage":"error persisting an entity of type: Task","errorMessageKey":"errors.cannotPersistEntity","errorCode":500,"errors":[{"detailMessage":"","propertyName":"","severity":"ERROR","type":"UNKNOWN_INTERNAL_ERROR"}],"entityName":"Task"}

### ISSUE THREAD

**Issue by eegz33** [bullhorn/dataloader#363]
Loading test file but have no idea what the 500 error is referring to?
[dataloader_2021-10-13_13.46.01.log](https://github.com/bullhorn/dataloader/files/7339558/dataloader_2021-10-13_13.46.01.log)
[TaskTestLoad.csv](https://github.com/bullhorn/dataloader/files/7339569/TaskTestLoad.csv)

As ever error message of little help!?

**Comment by ndickerson** [comment]
Hmm, not sure on this one. The best way to discover why an internal server error is occurring is to reduce your number of columns down to a small set that works, and start re-introducing columns until you find the one that breaks.
