### ISSUE TITLE
JobOrder Entity: Unable to update, Export data for CustomText25 field of JobOrder Entity in BH Staging environment

### ISSUE THREAD

**Issue by Shamshadbegam** [bullhorn/dataloader#368]
### Description
JobOrder Entity: Unable to update, Export data for CustomText25 field of JobOrder Entity in BH Staging environment

[Description of the issue]
JobOrder Entity: Unable to update, Export data for CustomText25 field of JobOrder Entity in BH Staging environment

### Steps to Reproduce

1. Connect to BH Staging Environment by updating section 3 details of Dataloader Property
2. Trying to export data so enabled the data loader property file with exist field jobOrderExistField=id
3. when trying to execute command Export in command propmpt getting error as 'customText25' does not exist on JobOrder

##### Expected behavior:

The data should be exported with customText25 for JobOrder entity

##### Actual behavior:

getting error as 'customText25' does not exist on JobOrder

##### Reproduces how often:

[What percentage of the time does it reproduce?]

### Additional Information

1. The `dataloader.properties` file (minus login info)
[dataloaderPropertyfile.txt](https://github.com/bullhorn/dataloader/files/7795984/dataloaderPropertyfile.txt)

2. The CSV input file (smallest possible file that reproduces the issue)
3. 
[JobOrderExportSample.csv](https://github.com/bullhorn/dataloader/files/7795986/JobOrderExportSample.csv)

3. The results file(s)
4. 
[JobOrderExportSample_export_2021-12-31_16.28.21_failure.csv](https://github.com/bullhorn/dataloader/files/7795988/JobOrderExportSample_export_2021-12-31_16.28.21_failure.csv)

4. The log file
[dataloader_2021-12-31_16.28.21.log](https://github.com/bullhorn/dataloader/files/7795990/dataloader_2021-12-31_16.28.21.log)

**Comment by Shamshadbegam** [comment]
Hi @ndickerson 

Request you to help on this.

Thanks,
Shamshad

**Comment by ndickerson** [comment]
This will just require updating Data Loader to use the latest SDK Rest to pick up newly added fields. Added this as a feature. Should be able to put out a new version this month (Jan 2022) with the new fields.

**Comment by Shamshadbegam** [comment]
Thanks a lot @ndickerson.

**Comment by Shamshadbegam** [comment]
Hi @ndickerson.

Could you please confirm if there is enhancement for the maximum number of records that can be processed for input CSV file using dataloader.

Thanks in Advance!!

Regards,
Shamshad

**Comment by ndickerson** [comment]
The data loader converts the CSV file into Rest API calls. There is no restriction on the number of records in a CSV file, just as there is no restriction on the number of rest calls that can be made over time. What sort of limit are you encountering?

**Comment by Shamshadbegam** [comment]
Hi @ndickerson 

During our initial discussion with BH team with Maria Eseberre on Dataloader we were notified that CSV file would be having a limit of 20k records which would be consumed for processing, Kindly let us know if this limit still applies?

Thanks in Advance!!

Regards,
Shamshad

**Comment by ndickerson** [comment]
That would be a guideline, not a technical limitation. Technically, the only limit is the size of your computer's memory.

**Comment by Shamshadbegam** [comment]
Thanks a lot @ndickerson

**Comment by ndickerson** [comment]
This has been fixed in release https://github.com/bullhorn/dataloader/releases/tag/v4.10.1. Coming to the Desktop App in the business day or two.
