### ISSUE TITLE
Candidate Insert Errors on SL 99

### ISSUE THREAD

**Issue by patricksey** [bullhorn/dataloader#369]
### Description

When loading candidates on SL 99 the first 350-550 records will insert without issue, then the following error is returned for all remaining records:

com.bullhornsdk.data.exception.RestApiException: {"errorMessage":"error persisting an entity of type: Candidate","errorMessageKey":"errors.cannotPersistEntity","errorCode":500,"errors":[{"detailMessage":"","propertyName":"","severity":"ERROR","type":"UNKNOWN_INTERNAL_ERROR"}],"entityName":"Candidate"}

### Steps to Reproduce

1. Load candidates for a new client (post 12/11/2021) on SL 99

##### Expected behavior:

Candidate to successfully import

##### Actual behavior:

First 350-500 insert and the rest fail out

We're thinking this whole thing may be related to an indexing issue and is not tied to the dataloader, but Bullhorn will push back if we don't go here first.

##### Reproduces how often:

Every new client on SL 99 since around 12/11/2021.  We could not reproduce the issue for our data sandbox (Corp ID: 20957)

### Additional Information
The following additional info is from client Parker Tide Corp. (Corp ID: 22341).  This company is going to be moved to a production SL tomorrow so we can finish importing test data.  We can provide another company if needed for testing.

1. The `dataloader.properties` file (minus login info)
[dataloaderproperties.txt](https://github.com/bullhorn/dataloader/files/7803801/dataloaderproperties.txt)

2. The CSV input file (smallest possible file that reproduces the issue)
Don't feel comfortable putting this information here, please reach out to me for the files.

3. The results file(s)
Don't feel comfortable putting this information here, please reach out to me for the files.

4. The log file
[dataloader_2022-01-03_09.41.55.log](https://github.com/bullhorn/dataloader/files/7803795/dataloader_2022-01-03_09.41.55.log)

**Comment by patricksey** [comment]
We're now experiencing the same issue on SL 34 as well.  Normally, moving the client to a production SL works around the issue, but it we're seeing the problem persist for Parker Tide. Please see the files below:

1. The dataloader.properties file (minus login info)
[dataloaderproperties-20220105.txt](https://github.com/bullhorn/dataloader/files/7816953/dataloaderproperties-20220105.txt)

2. The CSV input file (smallest possible file that reproduces the issue)
[candidate-20211228-rerun52.csv](https://github.com/bullhorn/dataloader/files/7816955/candidate-20211228-rerun52.csv)

3. The results file(s)
[candidate-20211228-rerun52_load_2022-01-05_08.14.45_success.csv](https://github.com/bullhorn/dataloader/files/7816956/candidate-20211228-rerun52_load_2022-01-05_08.14.45_success.csv)
[candidate-20211228-rerun52_load_2022-01-05_08.14.45_failure.csv](https://github.com/bullhorn/dataloader/files/7816957/candidate-20211228-rerun52_load_2022-01-05_08.14.45_failure.csv)

4. The log file
[dataloader_2022-01-05_08.14.45.log](https://github.com/bullhorn/dataloader/files/7816959/dataloader_2022-01-05_08.14.45.log)

**Comment by ndickerson** [comment]
Not sure how Data Loader could cause this directly, but you can tweak the performance settings to understand the nature of the internal errors on the swimlane.

Try setting numThreads=1 and see if it goes past the 500 mark.
Try setting caching=false and see if that has any effect.

**Comment by patricksey** [comment]
@ndickerson, lowering the thread count did work, but is there anything else to be done to work around this problem?  I can go to BH support if it's not a dataloader thing.

**Comment by ndickerson** [comment]
There is nothing else that can be done from the Data Loader client, it's happening due to behavior on the the servers.
