### ISSUE TITLE
Unable to load data into custom object ID > 10

### ISSUE THREAD

**Issue by dbroking-sixcel** [bullhorn/dataloader#371]
### Description

Unable to load data into custom object ID > 10

### Steps to Reproduce

1. Access data loader
2. Looking for PersonCustomObjectInstance13
3. not shown in pick list

##### Expected behavior:

Need to be able to load data into ALL Custom Objects

##### Actual behavior:

Limited to loading data into Custom Objects 1 - 10

##### Reproduces how often:

100%

### Additional Information

1. The `dataloader.properties` file (minus login info)
2. The CSV input file (smallest possible file that reproduces the issue)
3. The results file(s)
4. The log file

**Comment by ndickerson** [comment]
Added entities - will be in next release
