### ISSUE TITLE
Unable to load attachment for a Placement.

### ISSUE THREAD

**Issue by verma-monika** [bullhorn/dataloader#374]
### Description

Not able to load attachment for a specific placement
Error Received: com.bullhornsdk.data.exception.RestApiException: Cannot read file from disk: Attachments/2021 GM Worksheet_Eli Lilly_v2.xlsb

### Steps to Reproduce

1. CSV file prepared for data load: 
![image](https://user-images.githubusercontent.com/99537616/153709984-2c2a0ff9-f1be-4486-99da-3c542373dda7.png)
Mentioned these fields and data

The folder Attachments exist in data folder.

![image](https://user-images.githubusercontent.com/99537616/153710281-dcc28fd0-66f4-4b2a-aa38-56c05a580061.png)

2. In CMD, entered command after changing directory to dataloader: 
dataloader loadattachments C:\Users\us441501\Desktop\dataloader\data\PlacementAttachFile.csv

3. Received error in log: Cannot read file from disk: Attachments/2021 GM Worksheet_Eli Lilly_v2.xlsb

##### Expected behavior:

Attachment to get loaded to corresponding placement with ID 255901

##### Actual behavior:

Load failed with error: 
com.bullhornsdk.data.exception.RestApiException: Cannot read file from disk: Attachments/2021 GM Worksheet_Eli Lilly_v2.xlsb

##### Reproduces how often:

100%

### Additional Information

1. The `dataloader.properties` file (minus login info)
[Properties File.txt](https://github.com/bullhorn/dataloader/files/8053297/Properties.File.txt)

2. The CSV input file (smallest possible file that reproduces the issue): 
[PlacementAttachFile.csv](https://github.com/bullhorn/dataloader/files/8053294/PlacementAttachFile.csv)

3. The results file(s): 
[PlacementAttachFile_loadAttachments_2022-02-12_17.14.46_failure.csv](https://github.com/bullhorn/dataloader/files/8053291/PlacementAttachFile_loadAttachments_2022-02-12_17.14.46_failure.csv)

4. The log file: 
[dataloader_2022-02-12_17.14.46.log](https://github.com/bullhorn/dataloader/files/8053290/dataloader_2022-02-12_17.14.46.log)

**Comment by ndickerson** [comment]
Do all of the other file attachments load in your test data? Have you tried removing the white spaces from the attachment name?
