### ISSUE TITLE
Candidate field that auto-populates

### ISSUE THREAD

**Issue by SpotterGeri** [bullhorn/dataloader#375]
### Description

I am completely new to Bullhorn and GitHub so please be patient with me.  

When I am using the custom import tool from within BH to import candidate records, I have one field that auto-populates differently than when I use the Data Loader.  I cannot see in the Data Loader where this setting is located.

### Steps to Reproduce

1. Unknown

##### Expected behavior:

I expected the field to auto-populate with the same selection as it did when I used the Custom Import Tool - Note the field was not in the CSV.

##### Actual behavior:
The field is populated with a different selection.

##### Reproduces how often:

This happens with every entry.

### Additional Information

Thank you.

**Comment by ndickerson** [comment]
Which field on Candidate are you looking to populate?

**Comment by ndickerson** [comment]
Closing because of no response. Feel free to open a new issue for a specific question about data loader usage.
