### ISSUE TITLE
Date of Birth month not importing correctly

### ISSUE THREAD

**Issue by Lcooke89** [bullhorn/dataloader#376]
When I import a candidate with a DOB of "24/09/1980 05:00", it imports the month as January instead of September, this has happened multiple times. I am using the following date format in the settings of the data loader "dd/mm/yyyy HH:mm", I have also been told by Bullhorn that I need to add the "05:00" to the time as it gets uploaded in eastern time and will import a day prior if just left to 00:00. 

I get no errors during the import and everything else on the file imports successfully.

**Comment by ndickerson** [comment]
The use of `m` in the date format is minutes, not month. You'll need to capitalize the M for month.

```
"dd/MM/yyyy HH:mm"
```
