### ISSUE TITLE
Change Request mass upload ghost data

### ISSUE THREAD

**Issue by cookbd2** [bullhorn/dataloader#377]
### Description

We are attempting to make change requests (in submitted status) to mass upload events and running into random data showing up

### Steps to Reproduce

1. add change request csv and map correct fields
2. upload and review change request data mapping with only select fields
3. reject change request due to many required fields (do not see this ghost data anywhere as well)
4. upload and review different change request csv (with additional fields that previously were still showing up as the correct data)
5. approve change request, everything when it was in submitted status is correct

##### Expected behavior:

mirror fields from id of the record being referenced, then approve change request

##### Actual behavior:

random new data shows up in record

##### Reproduces how often:

unknown, have halted this process after one issue

**Comment by ndickerson** [comment]
Not sure where to go on this one. You'll probably need to troubleshoot what is happening in the ATS. You can view the dataloader log file to see exactly what rest calls were made, and compare that to manually creating the data in the ATS.

**Comment by ndickerson** [comment]
Another thing - you can try exporting the placement and the placement change request that's in question, and compare them to try and figure out exactly what data is being added.
