### ISSUE TITLE
Activity_ClientSubmissions : We want to update ClientContact for all records of Activity_ClientSubmissions but unable to find the sample file to consider to prepare input CSV file for dataloader

### ISSUE THREAD

**Issue by Shamshadbegam** [bullhorn/dataloader#378]
### Description

Activity_ClientSubmissions : We want to update ClientContact for all records of Activity_ClientSubmissions but unable to find the sample file in examples folder of dataloader to consider to prepare input CSV file for dataloader

[Description of the issue]
As part of Vanguard project we wanted to update ClientContact data for Activity_ClientSubmissions entity, Could you please help us with the sample input file and Existfield to be considered for update for the same.

we do not have this Activity_ClientSubmissions entity in Section3 of Dataloader Properties file.

Request you to help.

Thanks in Advance!!

Regards,
Shamshad

**Comment by ndickerson** [comment]
Is this a custom entity perhaps? The entities that Data Loader can load are all listed here: https://github.com/bullhorn/dataloader/wiki/Supported-Entities

**Comment by ndickerson** [comment]
The Activity_ClientSubmissions is not an entity, but Sendout is. The Sendout is the entity for ClientSubmissions. Give that a try.
