### ISSUE TITLE
Failed to create rest session

### ISSUE THREAD

**Issue by leonardosalatino** [bullhorn/dataloader#380]
### Description
Running dataloader with any of both:
./dataloader template ClientCorporation
./dataloader load ./data/ClientCorporation.csv
I also tried doing "npm run start" with the UI code, but facing the same issue in dataloader cli.

Is it possible this error is because I'm on kubuntu 22?

### Steps to Reproduce

1. Just run: ./dataloader load ./data/ClientCorporation.csv

##### Expected behavior:

To be able to upload the data.

##### Actual behavior:

Facing error: com.bullhornsdk.data.exception.RestApiException: Failed to create rest session

##### Reproduces how often:

Always, with any parameters

### Additional Information

[issue.zip](https://github.com/bullhorn/dataloader/files/8558517/issue.zip)
Attached:
1. The `dataloader.properties` file (minus login info)
2. The CSV input file (smallest possible file that reproduces the issue)
3. The log file

node --version
v16.14.2

java --version
openjdk 11.0.14.1 2022-02-08
OpenJDK Runtime Environment (build 11.0.14.1+1-Ubuntu-0ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.14.1+1-Ubuntu-0ubuntu1, mixed mode, sharing)

**Comment by ndickerson** [comment]
When you are unable to create a rest session, first verify your username/password credentials. Then review your clientId/clientSecret to see if you can login with those four. Then, you'll need to verify if the location you are running Data Loader on the command line from can connect from that particular network. Sometimes firewalls can prevent the Java executable jar file from connecting to the Bullhorn Rest API even if the username/password/clientId/clientSecret are all correct.

**Comment by leonardosalatino** [comment]
After a couple of times I resubmitted it started working.
Most of the times it works fine but I face that error from time to time, the same happens in windows. Seems that this is not related to dataloader, it is with Bullhorn API because (from time to time) I'm not able to generate tokens using Postman neither.
