### ISSUE TITLE
dataloader convertAttachments followed by the 'load' command

### ISSUE THREAD

**Issue by rachidouznag** [bullhorn/dataloader#384]
### Description

cannot understand how to execute the load command after a 'dataloader convertAttachments' operation

### Steps to Reproduce

So i managed to convert attachements (resume files) into an html version.
But what i can't seem to underantd is how to to get these html files to be parsed as new candidates in BH (just bare with me i'm new to all of this)

##### Expected behavior:

create candidates out the converted files, in the wiki it says "This action will need to be followed by the load command. When the load command is run, dataloader will check the convertedAttachments folder that was created and load any converted attachments that match an externalID in the CSV being read from."

is this what i need to use to created new candidates out of the converted files ? or is this not what i should follow to get things done ?

thank you in advance :)

**Comment by ndickerson** [comment]
As long as you specify a `candidate.externalID` column in the file attachment CSV file that you use with the convertAttachments command, see the example file here: https://github.com/bullhorn/dataloader/blob/v5.2.0/examples/load/attachments/Candidate.csv, it will take the files, convert them into the HTML format, and store them in the current directory, where the name of the folder for each record is equal to the name of the externalID of the record. Then, when you load, and use the same externalID, it will look in those folders, read the HTML of the files and insert them as the description field, or resume field.
