### ISSUE TITLE
Support for PersonCustomObjects 25-35

### ISSUE THREAD

**Issue by deniss-snitko** [bullhorn/dataloader#395]
### Description

Bullhorn Product added 25 extra Custom Objects to Person Entity to support Manpower France program (https://jira.bullhorn.com/browse/BH-71741).

Currently there is a total of 35 PersonCustomObjects available in the Bullhorn Schema.

Manpower France are relying on Data Loader Command Line to run initial test/data load across 4 NPE environments and PROD.

Could we please ensure that all 35 Person Custom Objects are available via Data Loader.

**Comment by ndickerson** [comment]
This is now supported in the latest release: https://github.com/bullhorn/dataloader/releases
