### ISSUE TITLE
needed latest version of Bullhorn dataloader V2.8 to install

### ISSUE THREAD

**Issue by Maximehuot** [bullhorn/dataloader#417]
Where can I find the latest version of Bullhorn dataloader V2.8 to install for my new computer ?
I have tried to install a former version V2.2.1 but it didn't work

**Comment by ndickerson** [comment]
Download the latest installer for [Windows](https://github.com/bullhorn/dataloader-app/releases/download/v2.9.1/Bullhorn-Data-Loader-Setup-2.9.1.exe) or [Mac](https://github.com/bullhorn/dataloader-app/releases/download/v2.9.1/Bullhorn-Data-Loader-2.9.1.dmg)

https://github.com/bullhorn/dataloader-app
