### ISSUE TITLE
Technical Error Getting Meta Data after selecting entity.

### ISSUE THREAD

**Issue by ehogue-oaktree** [bullhorn/dataloader#434]
### Description

Tried using dataloader today and have used ealier this year just fine. The version installed showed the error getting meta data with note about jre version not being 1.8. I checked the jre and uninstalled and reinstalled. It seems that is still the same version. The current jre is 1.8 bild 411. Then I found a newer 4.11 v  of dataloader so I installed that one. It just simply stated just the error message without a note about jre versions, etc.

The log file seems ok and end with line: Done generating meta for Placement

### Steps to Reproduce

1. Load csv and click next
2. Select Placements entitie and click next.
3. error pops up

##### Expected behavior:

It generally comes to mapping, etc. steps

##### Actual behavior:

it stops at step 3

##### Reproduces how often:

100% even with other entities.

### Additional Information

1. The `dataloader.properties` file (minus login info)
2. The CSV input file (smallest possible file that reproduces the issue)
3. The results file(s)
4. The log file
[plc-soc-fix-export.csv](https://github.com/bullhorn/dataloader/files/15028984/plc-soc-fix-export.csv)
[dataloader_2024-04-18_13.14.57.log](https://github.com/bullhorn/dataloader/files/15028988/dataloader_2024-04-18_13.14.57.log)
[dataloader.properties.txt](https://github.com/bullhorn/dataloader/files/15029038/dataloader.properties.txt)

**Comment by ndickerson** [comment]
Is this an issue with the Desktop App that is calling meta in order to map columns to meta? Is it failing in the App for you? The meta call should not be used except by the Desktop app, since the purpose is to print the computed meta to standard output for the App to consume and use for column mapping.

**Comment by ehogue-oaktree** [comment]
Nathan,

Yes I'm in the desktop app - just installed the lastest download for it also and still getting the same error with less info.

One thing I noticed, is going to validate credentials I thought it used to popup a message successful. It doesn't do that now, if it did it in past. But those all appear still correct.

Any suggestions. I last used this in Feb and it was fine.
Thanks


Eddie Hogue
Information Technology
Phone 918-584-7900

________________________________

**Comment by ndickerson** [comment]
If there's no successful popup message and there's no parsing of Meta happening, then that would point to a breakdown between the dataloader command line app that writes to stdout and the parent electron node app that spawned the dataloader command line java executable and is scraping the output from it. 

My guess is that something like a virus scanning software has prevented such communication within the electron app and it's child java process it spawns. Maybe check a different computer or setup?

**Comment by jenspeer** [comment]
Hi! I'm having this same issue. Our IT department couldn't identify any software that is interfering with java.

**Comment by ndickerson** [comment]
If you execute the following command from dataloader, what gets output to the command line?

`dataloader login`

You should see "Login Successful" or "Login Failed" printed to the command line.

**Comment by ehogue-oaktree** [comment]
I just turned off the Windows Defender  with no change in the error. The cmd window that comes up runs a lot of giberous just before closing then the error pops up.

When I check credentials I get the cmd window and it just goes away - I think it used to popup a UI window the authentication was successful.


Eddie Hogue
Information Technology
Phone 918-584-7900

________________________________

**Comment by ndickerson** [comment]
RIght. The check credentials is using `dataloader login` behind the scenes, communicating that to the dataloader command line app. If you open up the dataloader command line app on your computer, can you get the login command to output something, or is output broken?

**Comment by ehogue-oaktree** [comment]
I found the Bullhorn Data Loader.exe finally and

Checking for update
[14516:0418/151036.857:ERROR:cache_util_win.cc(20)] Unable to move the cache: Access is denied. (0x5)
[14516:0418/151036.857:ERROR:cache_util_win.cc(20)] Unable to move the cache: Access is denied. (0x5)
[14516:0418/151036.873:ERROR:disk_cache.cc(208)] Unable to create cache
[14516:0418/151036.873:ERROR:gpu_disk_cache.cc(676)] Gpu Cache Creation failed: -2
[14516:0418/151036.873:ERROR:disk_cache.cc(208)] Unable to create cache
[14516:0418/151036.873:ERROR:gpu_disk_cache.cc(676)] Gpu Cache Creation failed: -2
15:10:37.551 > Update for version 2.11.1 is not available (latest version: 2.11.1, downgrade is disallowed).
15:10:37.552 > checkForUpdatesAndNotify called, downloadPromise is null

Where is this cache location that it would be getting Access is denied on?

Thanks


Eddie Hogue
Information Technology
Phone 918-584-7900

________________________________

**Comment by ndickerson** [comment]
That is the electron log updater that checks for latest versions from github. Those errors shouldn't matter - it's just trying to determine if it has the latest version or not of the electron app. The issue you're asking about seems to be a problem with the output of the dataloader java command line application itself.

**Comment by ehogue-oaktree** [comment]
Any way to get the command line output to run and see what it is doing?

I'm not seeing how to view the command line.

Eddie Hogue
Information Technology
Phone 918-584-7900

________________________________

**Comment by ehogue-oaktree** [comment]
There is no login successful or failed output though.

Eddie Hogue
Information Technology
Phone 918-584-7900

________________________________

**Comment by ehogue-oaktree** [comment]
Hi Nathan

I ran through a complete attempt and here is the output in the command window all the way up to the Meta Data Error from UI.

"bullhorn data loader.exe" login

C:\Users\ehog\AppData\Local\Programs\dataloader-ui>
15:29:39.522 > Checking for update
15:29:43.535 > Update for version 2.11.1 is not available (latest version: 2.11.1, downgrade is disallowed).
15:29:43.537 > checkForUpdatesAndNotify called, downloadPromise is null
15:30:15.246 > Start: received 16 params
15:30:15.258 > Resolved User Data location: C:\Users\ehog\AppData\Roaming\Bullhorn Data Loader
15:30:15.260 > Resolved Data Loader location: C:\Users\ehog\AppData\Local\Programs\dataloader-ui\resources\app.asar.unpacked\dataloader
15:30:15.265 > Resolved Jar File: dataloader-5.10.1.jar
15:30:15.274 > Spawned dataloader process with pid: 2928
15:30:15.454 > Java Version Check: java version "1.8.0_411"
Java(TM) SE Runtime Environment (build 1.8.0_411-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.411-b09, mixed mode)

15:30:18.325 > Process exit. code: 0, signal: null
15:30:18.326 > Process closed - sending 'done' signal to UI

Eddie Hogue
Information Technology
Phone 918-584-7900

________________________________

**Comment by ndickerson** [comment]
So, the App is just executing the dataloader command line java process in a spawned thread. This issue started off with running the `meta Placement` command directly in dataloader to cut out the App layer, which is smart. What happens on the command line when you ignore the App and go straight to dataloader and execute: `dataloader login`. That is what we need to establish - what's the command line output? Is that somehow now outputting anything from Java?

**Comment by jenspeer** [comment]
This was an adventure since I have never used the command prompt and only used the desktop application (which is where I'm getting the error). After following the instructions for accessing the command prompt, my command prompt says: Login Successful

Still not able to log in on the desktop application v2.11.1.

**Comment by ehogue-oaktree** [comment]
When I run the login command from cmd line I don't get the login sucessful message at all, but the UI opens up like it is ready to go. Now I only get the following cmd output.

15:48:36.452 > Checking for update
15:48:37.588 > Update for version 2.11.1 is not available (latest version: 2.11.1, downgrade is disallowed).
15:48:37.589 > checkForUpdatesAndNotify called, downloadPromise is null

If I use the UI to load the csv, select entity then it still pops up the meta error and the output in the cmd window is 
15:52:47.105 > Start: received 16 params
15:52:47.120 > Resolved User Data location: C:\Users\ehog\AppData\Roaming\Bullhorn Data Loader
15:52:47.121 > Resolved Data Loader location: C:\Users\ehog\AppData\Local\Programs\dataloader-ui\resources\app.asar.unpacked\dataloader
15:52:47.128 > Resolved Jar File: dataloader-5.10.1.jar
15:52:47.134 > Spawned dataloader process with pid: 23152
15:52:47.267 > Java Version Check: java version "1.8.0_411"
Java(TM) SE Runtime Environment (build 1.8.0_411-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.411-b09, mixed mode)

15:52:50.127 > Process exit. code: 0, signal: null
15:52:50.128 > Process closed - sending 'done' signal to UI

I briefly see the java window but not able to any details in it.

**Comment by ndickerson** [comment]
Hmm, so that means that the dataloader command line is working properly on your machine, but the interaction between the App and the command line seems to be broken somehow. Have you tried uninstalling and reinstalling the app?

**Comment by ehogue-oaktree** [comment]
yes - i uninstalled both jre and dataloader and reloaded them. jre stayed the same version but dataloader was 2.11.1 being newer than I had installed previously.

**Comment by jenspeer** [comment]
Yes as well. Uninstalled, reinstalled, problem persists.

**Comment by ndickerson** [comment]
I'm not sure how to help beyond this. I can't repro this issue on my machine. I'm on a Mac. You can try to use a different machine and try to narrow down what machine conditions lead to this. Perhaps others can weight in if they are experiencing it working, and what OS they are using?

**Comment by aburton95** [comment]
@ndickerson I am receiving the same 'Technical Error Receiving Meta Data.' I am on version 2.9.1.

**Comment by ndickerson** [comment]
This is a new bug I haven't seen before. I just released a new version of the Data Loader App with the very latest dependencies. See if this helps the problem. It should auto-update when you open the App to [Version 2.11.2](https://github.com/bullhorn/dataloader-app/releases).

**Comment by jenspeer** [comment]
@ndickerson This update did not work for me. I'm getting the same error.

**Comment by ndickerson** [comment]
Folks have mentioned that this started happening after Java update [JDK 8u411](https://www.oracle.com/java/technologies/javase/8u411-relnotes.html). I have this version on a Mac and I'm not seeing the issue.

**Comment by ehogue-oaktree** [comment]
Will try it next week
Thanks

Eddie Hogue
OakTree Staffing

________________________________

**Comment by n-ellison** [comment]
I'm having the same issue as the others.  I have the command line version installed on another machine and it is working fine, but the desktop app is not.  

This is the error in the App Console:

main.6818e34cc61932b9.js:1 Uncaught TypeError: Cannot read properties of null (reading 'fields')
    at Function.value (main.6818e34cc61932b9.js:1:5704679)
    at main.6818e34cc61932b9.js:1:5701778
    at Array.map (<anonymous>)
    at main.6818e34cc61932b9.js:1:5701659
    at f.invoke (polyfills.72b665462a35e4da.js:1:7652)
    at Object.onInvoke (main.6818e34cc61932b9.js:1:8862221)
    at f.invoke (polyfills.72b665462a35e4da.js:1:7592)
    at f.run (polyfills.72b665462a35e4da.js:1:2727)
    at l.value (main.6818e34cc61932b9.js:1:8862679)
    at i.value (main.6818e34cc61932b9.js:1:5701461)

**Comment by ehogue-oaktree** [comment]
Just downloaded and installed this version and still the same. Looking at trying to get an older version of jre before 8u411 to try.

Eddie Hogue
Information Technology
Phone 918-584-7900

________________________________

**Comment by jenspeer** [comment]
Uninstalling the latest Java update and reinstalling the previous version fixed the issue for me. However, our IT department warns that this is not a long-term solution as previous versions of Java can be unstable and less secure.

**Comment by ehogue-oaktree** [comment]
would you happen to have the download link to a previous version? That's what I'm looking for at the moment.

Eddie Hogue
Information Technology
Phone 918-584-7900

________________________________

**Comment by ndickerson** [comment]
All installers (.exe files) can be downloaded here: https://github.com/bullhorn/dataloader-app/releases

**Comment by ehogue-oaktree** [comment]
Yes, I got the latest dataloader downloaded and installed. I'm trying to find an older version of jre to install.

Eddie Hogue
Information Technology
Phone 918-584-7900

________________________________

**Comment by ndickerson** [comment]
Try this page: https://www.oracle.com/java/technologies/javase/javase8u211-later-archive-downloads.html

**Comment by ehogue-oaktree** [comment]
I downloaded jdk-8u401-windows-x64 and now dataloader works as expected.

something with 411 windows x64 that dataloader doesn't like.


Eddie Hogue
Information Technology
Phone 918-584-7900

________________________________

**Comment by n-ellison** [comment]
Thanks, guys.  Rolling back to an earlier version of Java did the trick for me too.

**Comment by ndickerson** [comment]
I was just able to repro the issue we are seeing with Java version 411 on windows. The behavior of java processes (aka: the Data Loader CLI) changed so it now exits before returning output. I have a plan for fixing this. I should have a fix ready soon that works around this issue.

**Comment by ehogue-oaktree** [comment]
good deal and good luck

Eddie Hogue
OakTree Staffing

________________________________

**Comment by ndickerson** [comment]
I just released a new version of the Desktop App, which will auto-update the next time you open it, and should fix issues we are seeing with the latest Java update. Let me know if that fixes this issue we are seeing.  https://github.com/bullhorn/dataloader-app/releases

**Comment by ehogue-oaktree** [comment]
I will give it a test for you next week. Trying to get home from Engage

Eddie Hogue
Information Technology
Phone 918-584-7900

________________________________

**Comment by ehogue-oaktree** [comment]
Nathan
I just let java update to 411 and after loading the new 2.11.3 dl everything is fine.

Thanks

Eddie Hogue
Information Technology
Phone 918-584-7900

________________________________
