### ISSUE TITLE
# in front of ExistFields in the property file

### ISSUE THREAD

**Issue by ccoffman1** [bullhorn/dataloader#80]
Hello,

Not sure if this was by design or not but currently all of the ExistFields are saved with the # in front of it (turns it green in notepad++ like it is being commented out) and when running an update based on id and updating a single field it inserts a new record with only the the one field.  Tested this two times each way and it inserted both times with the # still on the end.

Removing the # allows it to update just fine.  Not sure if this is as designed but being a change from the previous versions I assumed not.

**Comment by ndickerson** [comment]
Added documentation about the `ExistField`s to the README.md.
