### ISSUE TITLE
v2.1.1 data type for to-many entities has changed to Integer rather than String

### ISSUE THREAD

**Issue by davidrendall** [bullhorn/dataloader#91]
For example, in v2.1.0 the CSV template example business sectors for candidate are written with header "businessSectors.name" and data type "String". In v2.1.1, the header is "businessSectors.id" with data type "Integer". This seems misleading to me because the content of that field should always be a comma-separated list of names of business sectors, not a list of numeric IDs? Or have I missed something...?

**Comment by ndickerson** [comment]
Hi David, thanks for asking - we did recently change the template functionality to be exactly what is supported by SDK-REST, for consistency and correctness. We fixed an issue where we used to output multiple associated record types - `businessSectors.id`, `businessSectors.name`, which would have bad behavior if you tried to load an input CSV file with columns like that. We came to conclusion that we would simply use the `.id` extension for all associated fields and let the user change that associated field from `id` to any field of their choosing. It works as a selector, so you can target any field that makes sense for your input data.  We've just updated our documentation in the readme and wiki to reflect the new template behavior.  https://github.com/bullhorn/dataloader/wiki/Commands#template

**Comment by davidrendall** [comment]
Hi Nathan, thanks for the quick reply and the great explanation, it makes perfect sense now!
